apiVersion: v1
kind: Service
metadata:
  name: adservice-svc
spec:
  selector:
    app: adserve
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: adserve
  template:
    metadata:
      labels:
        app: adserve
    spec:    
      containers:
        - name: adservice
          image: harfoh/adservice:v1.0.0

