apiVersion: v1
kind: Service
metadata:
  name: checkout-svc
spec:
  selector:
    app: check
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-deployment
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: check
  template:
    metadata:
      labels:
        app: check
    spec:    
      containers:
        - name: check
          image: harfoh/checkout:v1.0.0
          env:
            - name: CURRENCY_SERVICE_ADDR
              value: "currency-svc.default"
            - name: CART_SERVICE_ADDR
              value: "cart-svc.default"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendation-svc.default"
            - name: AD_SERVICE_ADDR
              value: "adservice-svc.default"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkout-svc.default"
            - name: EMAIL_SERVICE_ADDR
              value: "email-svc.default"
            - name: LOADGENERATOR_SERVICE_ADDR
              value: "loadgen-svc.default"
            - name: PAYMENT_SERVICE_ADDR
              value: "payment-svc.default"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "product-svc.default"
            - name: SHIPPING_SERVICE_ADDR
              value: "shipping-svc.default"

