apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:    
      containers:
        - name: front
          image: harfoh/frontend:v1.0.0
          env:
            - name: CURRENCY_SERVICE_ADDR
              value: "currency-svc.default:7000"
            - name: CART_SERVICE_ADDR
              value: "cart-svc.default:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendation-svc.default:8080"
            - name: AD_SERVICE_ADDR
              value: "adservice-svc.default:9555"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkout-svc.default:5050"
            - name: EMAIL_SERVICE_ADDR
              value: "email-svc.default:8080"
            - name: LOADGENERATOR_SERVICE_ADDR
              value: "loadgen-svc.default"
            - name: PAYMENT_SERVICE_ADDR
              value: "payment-svc.default:50051"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "product-svc.default:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "shipping-svc.default:50051"
            - name: SHOPPING_ASSISTANT_SERVICE_ADDR
              value: "shopping-svc.default"

