# apiVersion: v1
# kind: Service
# metadata:
#   name: loadgen-svc
# spec:
#   selector:
#     app: load
#   ports:
#     - protocol: TCP
#       # port: 8080
#       # targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: load
  template:
    metadata:
      labels:
        app: load
    spec:    
      containers:
        - name: load
          image: harfoh/loadgen:v1.0.0

