apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: pay
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  port: "50051"
  disable_profiler: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:  
      app: pay
  template:
    metadata:
      labels:
        app: pay
    spec:    
      containers:
        - name: pay
          image: harfoh/payment:v1.0.0
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: port
            - name: DISABLE_PROFILER
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: disable_profiler
