apiVersion: v1
kind: Service
metadata:
  name: recommendation-svc
spec:
  selector:
    app: recommend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: recommend-config
data:
  pythonunbuffered: "1"
  port: "8080"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: recommend
  template:
    metadata:
      labels:
        app: recommend
    spec:    
      containers:
        - name: recommendation
          image: harfoh/recommendation:v1.0.0
          env:
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: recommend-config
                  key: pythonunbuffered
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: recommend-config
                  key: port          
            - name: CURRENCY_SERVICE_ADDR
              value: "currency-svc.default"
            - name: CART_SERVICE_ADDR
              value: "cart-svc.default"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendation-svc.default"
            - name: AD_SERVICE_ADDR
              value: "adservice-svc.default"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkout-svc.default"
            - name: EMAIL_SERVICE_ADDR
              value: "email-svc.default"
            - name: LOADGENERATOR_SERVICE_ADDR
              value: "loadgen-svc.default"
            - name: PAYMENT_SERVICE_ADDR
              value: "payment-svc.default"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "product-svc.default"
            - name: SHIPPING_SERVICE_ADD
              value: "shipping-svc.default"

