apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: red
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: red
  replicas: 1
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
        - name: redis
          image: redis
