name: CartService build, scan, and push images to Hub
on: push
jobs:
  build_and_snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build a Docker image
      run:  docker build -f ./src/cartservice/src/Dockerfile -t harfoh/cart:v1.0.0 ./src/cartservice/src
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: harfoh/cart:v1.0.0
        args: --file=./src/cartservice/src/Dockerfile     
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push to Hub
      run: docker push harfoh/cart:v1.0.0